---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
```

## Question 1 
```{r}
customer_base %>% 
  clean_names()

card_base %>% 
  clean_names() 

fraud_base %>% 
  clean_names()

Transaction_base %>% 
clean_names()

customer_base
card_base
fraud_base
Transaction_base
```

```{r}
Transaction_base <- Transaction_base %>% 
  rename("Card_Number" = "Credit_Card_ID")
```


## Question 2

```{r}
left_join(card_base, customer_base, by = "Cust_ID")
```

## Question 3

```{r}
full_join(fraud_base, Transaction_base, by = "Transaction_ID")
```

The resulting row number shows that all the data from "Transaction_base" has carried over and you can also see that matches from "fraud_base" is shown first. 

## Question 4

```{r}
semi_join(card_base, Transaction_base, by = "Card_Number")
```

## tidyr 

##Question 5

```{r}
hat_observations <- hat_observations %>% 
  separate(observation, c("colour", "style"), sep ="\\,")

hat_observations
```

## Question 6

```{r}
date_observed <- hat_observations %>% 
  unite(date, c("day", "month", "year"), sep = "/")
```

```{r}
date_observed %>% 
  filter(style == "beret") %>% 
  arrange(desc(observation_count))
```
The most berets were observed on 18/6/2018

## extension 

## Question 1

```{r}
card_base %>% 
  inner_join(customer_base, by = "Cust_ID") %>% 
  full_join(Transaction_base, by = "Card_Number") %>% 
  left_join(fraud_base, by = "Transaction_ID") %>% 
  filter(Fraud_Flag >= 1)
```

