---
title: "r_programming_hw"
output: html_notebook
---

```{r}
library(tidyverse)
```


## Question 1
```{r}
Glasgow_weather <- list(
  Thursday = list(rainfall = "1mm", wind_speed = "5-12mph", temperature = "14oc"),
  Friday = list(rainfall = "0mm", wind_speed = "5-12mph", temperature = "12oc"),
  Saturday = list(rainfall = "0mm", wind_speed = "4-12mph", temperature = "149c")
)

Glasgow_weather
```

##Question 2
i
```{r}
Glasgow_weather$Thursday$rainfall
```

ii
```{r}
Glasgow_weather$Friday$wind_speed
```

iii
```{r}
Glasgow_weather$Thursday$temperature
```

## Question 3
```{r}
week1_temps <- c(11, 10, 10, 10, 9, 9, 9)
week2_temps <- c(9, 9, 8, 11, 10, 12, 11)

portree_temp <- matrix(
  c(week1_temps, week2_temps),
  nrow = 2, 
  byrow = TRUE)  
  
colnames(portree_temp) <- c("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun") 
  
rownames(portree_temp) <- c("Week 1", "Week 2")

portree_temp
```


## Question 4 
i
```{r}
portree_temp[2, 3]
```

ii
```{r}
portree_temp[2, ]
```

iii
```{r}
portree_temp[ ,c(1, 3, 5)]
```

##Question 5
```{r}
verb <- function(x) {
  if (is.character(x)) {
    return(paste0("The answer is: ", x))
  } else if (is.numeric(x)) {
    if (x < 10) {
      return(x)
    } else if (x >= 10) {
      return(x/10)
    }
  } else {
    return("Invalid input")
  }
}
```

Couldn't think of a good name and best practice says we should try and use a "verb"
```{r}
verb("ten")
verb(9)
verb(100)
verb(t)
```

## Question 6

my brain has decided to stop functioning for the day
```{r}
check_vectors <- function(vec1, vec2) {
  if (length(vec1) != length(vec2)) {
    return("Different")
  } else if (all(vec1 == vec2)) {
    return("Exactly the same")
  } else if (all(sort(vec1) == sort(vec2))) {
    return("The same")
  } else {
    return("Different")
  }
}
```
 
 